### ISSUE TITLE
What constrains the performance of dual GPUs?

### ISSUE THREAD

**Issue by shouyiwang** [turboderp/exllama#134]
I apologize for posting my query here, but the discussion section appears to be rather inactive.

Upon reviewing the README information, I noticed that when employing dual GPUs, the token generation speed of the 65B model is substantially slower compared to the speed of a single 33B model on each GPU.

I’ve made a similar observation: when utilizing dual GPUs, the individual usage rates hover around 60-70%. This is significantly lower compared to using only one GPU which is over 90% utilization.

Initially, I suspected that the PCI-E bandwidth between the GPUs might be the constraining factor. However, upon limiting the PCI-E speed to 1X, I found no notable impact on the performance. Currently, the PCI-E speed is configured at 8x + 8x.

For additional context, my system is equipped with a 7950X and has ample RAM bandwidth (DDR5 6000), but these components don’t appear to be hindering factors anyway.

Does anyone know the reason behind it?

**Comment by EyeDeck** [comment]
>Initially, I suspected that the PCI-E bandwidth between the GPUs might be the constraining factor. However, upon limiting the PCI-E speed to 1X, I found no notable impact on the performance. 

Huh, I always figured PCI-E bus speed would be meaningful for this purpose. Now I'm curious how a bunch of cards on mining risers would fare, given the practical complications of connecting more than 2 GPUs up to a typical motherboard otherwise.
(Apologies that I haven't got anything more to add.)

**Comment by turboderp** [comment]
>I apologize for posting my query here, but the discussion section appears to be rather inactive.

It's only inactive because people keep raising issues whenever they have a comment or a question. ;)

Anyway, ExLlama doesn't use multiple devices in parallel. It's surprising if you can get over 50% utilization per GPU, actually, because that shouldn't be happening. The GPUs work in turn and there's only a small amount of data to pass between them at the point where the model is split, which is why PCIe bandwidth doesn't make much of a difference.

I can't speak to what Llama.cpp does. They've got a lot of talented people working on that project, and I'm not surprised they've been able to implement some solution for parallelism. It's not a trivial thing. I don't doubt I could do it if I had infinite time or maybe someone wanted to contribute with a core feature like that. But for now I have to prioritize, and ~20 tokens/second on 65b isn't prohibitively slow, so I'm more concerned with the limited context size of 65b on a dual 24 GB GPU setup. I need to explore the options that have opened up with the latest NVIDIA driver, and also I'm experimenting with some novel quantization methods that might reduce memory requirements overall.

**Comment by shouyiwang** [comment]
@turboderp 
The initial tests were conducted on a hybrid platform comprising of a 3090 and a 4090 GPU. 
Based on the utilization rate of the 3090 (Exllama 60%+, llama.cpp 85%+ ), I made an inference on the actual speed if both graphics cards were 3090s. Later on, I realized that such inference might not be accurate. 
I managed to get another 3090 later today and conducted the tests again with two 3090s. 
I discovered that the average GPU utilization rate for exllama was 40%, while for llama.cpp it was 60%.  And it indeed matches exllama's speed. Both are around 12- 13 tokens/s. Around 20% slower than 3090+4090.
Thank you so much for the explanation. I'll close the "issue".
