### ISSUE TITLE
Dual GPU setup on 13900k

### ISSUE THREAD

**Issue by SinanAkkoyun** [turboderp/exllama#164]
Hi!
We are considering buying a dual 4090 13900k rig for ExLlama LLM inference, but given the PCIe configurations,
(1x16 + 4 or 2x8 + 4)
we're not entirely sure if the 13900k is our best option and we want to be certain before we commit to such an investment.

I noticed that you own a dual GPU setup with a 12900k, would it please be possible for you if you could reconfigure your rig to use 16 lanes for the 4090 and rerun the benchmarks for 3B, 7B and 33B? (or vice-verca if the README benchmarks are based on single GPU)
Your guidance would be invaluable and could greatly help us in making our decision.

I fully appreciate that this is no small request, especially considering your busy schedule, I hope that I'm not imposing too much. I understand you are quite busy, but your expertise and knowledge would be invaluable in guiding us on this purchase.

If you could spare the time, I would greatly appreciate it. I totally understand that this time investment might come with costs, I would be happy to cover them of course.
Thank you so much for the great support!

**Comment by jmoney7823956789378** [comment]
Check out some of the info in here: https://github.com/turboderp/exllama/discussions/16#discussioncomment-6243456
Typically the amount of PCIe lanes doesn't really affect inferencing on exllama, due to the nature of the split method used.

**Comment by EyeDeck** [comment]
Yeah, right now, for ExLlama specifically, PCIe lanes aren't really a big consideration. You could probably run everything on PCIe 2.0 x1 mining risers and you wouldn't notice any difference except increased model load times. All that needs to be transferred from one card to another is on the order of a few kilobytes, per token, per card, per second. I doubt you could hit 1MB/s, and a single PCIe 2.0 lane is 500MB/s.

In the future, if ExLlama gets proper GPU parallelism, you would _probably_ want more than mining risers. Maybe. It's hard to say since the code doesn't exist yet. If I were looking to future-proof, and _had_ to choose one or the other, PCIe 4.0 8 x 2 would _probably_ be a safer bet.
Having a setting to choose 16+4 or 8+8 used to be a common BIOS/UEFI feature, like for example I remember ASRock specifically loved throwing that feature on even really budget boards back in the PCIe 3.0 days. I had a look through the manuals for a bunch of random Z790 boards, and it doesn't seem to start showing up, from any manufacturer, until you get up to mid-tier ~$300 boards though. Hmm...

**Comment by turboderp** [comment]
I already have the 4090 in a PCIe 4.0 x16 slot. But as the others are pointing out, the PCIe bandwidth doesn't really matter. With tensor parallelism maybe some time in the future it could start to matter, although for that purpose even 4.0 x16 might be too slow and you'd want something like NVLink (i.e. some number of 3090s might perform better than the same number of 4090s (!)). But it's way too early to tell just yet.

For now, if you're running with a single GPU, the total size of what gets sent over the PCIe bus, for any forward pass:

- `hidden_dim * seq_len * 2` bytes at the start of the forward pass
- `vocab_size * seq_len * 4` bytes at the end of the forward pass

`vocab_size` is always 32000, `hidden_dim` is between 3200 and 8192 depending on the model, and `seq_len` will typically be 1 when you're generating a token at a time. So we're talking a few kilobytes per token. It would be impossible to measure the difference between PCIe 3.0 x4 and PCIe 4.0 x16, for instance.

**Comment by SinanAkkoyun** [comment]
Thank you all for the great, detailed and helpful answers :)
I am glad that PCIe bandwidth plays no role at the moment. This would mean that one could also connect more GPUs to the M.2 PCIe 4x slots (even though there might be some overhead due to the PCH routing, idk if that is negligible?) of a normal motherboard I guess

I very much appreciate the help!

**Comment by dinvlad** [comment]
Does this also imply using multiple nodes could also be an option, without negative effect on performance?

**Comment by SinanAkkoyun** [comment]
@dinvlad Interesting idea, I'd also like to know that

**Comment by turboderp** [comment]
There's no support for it currently, but the amount of data moving between layers is quite small. So you wouldn't need a lot of bandwidth between nodes, no.
