### ISSUE TITLE
How to use 3k context size with Llama2?

### ISSUE THREAD

**Issue by vadi2** [turboderp/exllama#167]
How can one use 3k context size with Llama2? Trying out such a size makes the python process hog one core indefinitely.

**Comment by turboderp** [comment]
What's your setup and what front-end are you using? On ExLlama's web UI you'd just add `-l 3000` on the command line. Llama2 supports up to 4096 tokens natively so you won't need to do anything else. Beyond that size you'll need to specify a higher `--alpha` value.

**Comment by vadi2** [comment]
Thanks for the quick response! I'm Ubuntu 22.04, 32gb ram, RTX 4080 with 16gb vram - using ExLlama's webui is where it goes wrong. Seems to work fine in text-gen-ui using exllama backend.

Here's a screencast -

[Screencast from 19-07-23 18:20:09.webm](https://github.com/turboderp/exllama/assets/110988/950b0d3c-a653-4a41-a1da-59b094152450)

Notice the `python` process is at 8% - and it'll be like that for a while without progress.

**Comment by turboderp** [comment]
It seems to be an oversight in how it truncates the context. My guess is that block of text ends up being longer than the total context length, so it gets stuck in a loop where it has to trim the whole block from the context, but it also won't trim the very last item.

I'm not really sure how to address it, though. I guess it could fail more gracefully, but there really isn't any underlying support for working with partial text blocks, so it would be a bit of a rewrite to enable that, and I'm not sure what good it would do since you'd get an incorrect response to the prompt in any case, if it gets truncated.

**Comment by turboderp** [comment]
Well, I added that anyway. If you try it again it should work, unless you're encountering some other bug.

**Comment by vadi2** [comment]
Thanks, can confirm python process freezing is gone now and the output acts like it's been cut off. I've added a PR to give some sort of a warning that truncation is happening, what do you think? https://github.com/turboderp/exllama/pull/169

Closing issue as problem is fixed
