### ISSUE TITLE
Unsupported tensor dtype when applying certain LoRAs

### ISSUE THREAD

**Issue by BugReporterZ** [turboderp/exllama#170]
https://huggingface.co/Mikael110/llama-2-13b-guanaco-qlora

I'm reporting this on behalf of other users so I can't test it directly. It appears that when certain LoRA adapters are applied to a model using Exllama the operation will fail with an `unsupported tensor dtype in adapter_model.bin` error. The model loaded with regular `transformers` appears to accept the LoRA without issue.

It seems these LoRA adapters were trained with QLoRA, which encourages the user to use **BFloat16** during training if supported by the GPU.

![image](https://github.com/turboderp/exllama/assets/26941368/052a470c-5138-4b7a-9293-a4e5e8f2fb95)

Is this actually the reason this fails? If yes, are then plans to implement BF16 to FP16 conversion in Exllama when dealing with LoRAs?

**Comment by turboderp** [comment]
I don't have time to download the adapter right now, but if it's *saved* in BF16 then that would fail, yes.

There are hardly any standards in this field, so it's impossible to predict what someone will come up with next. I tried to find a good sampling of LoRAs but I never encountered one saved in BF16 before so I don't know what sort of accuracy loss to expect from converting it to FP16.

Converting it isn't a problem, it's just two more lines in `lora.py`:

            if tensor.dtype == torch.float16:
                pass

            elif tensor.dtype == torch.float32:
                tensor = tensor.to(torch.float16)

            elif tensor.dtype == torch.bfloat16:
                tensor = tensor.to(torch.float16)

            else: raise ValueError(f" ## Error: unsupported tensor dtype in {self.lora_path}")

But I'm a little wary because while I've confirmed that FP32->FP16 conversion performs reasonably well, in case BF16->FP16 produces poor results it could lead to a bunch of very confused bug reports about people being vaguely unsatisfied with the output quality.

I'll have a look later to see if I can figure out how much it matters in this particular case.

**Comment by BugReporterZ** [comment]
If needed, here are a couple other Llama2 LoRAs seemingly trained with BF16 format/Artidoro QLoRA and that other users have reported issues loading with Exllama, although I guess the custom prompt format would make them difficult to easily debug: 

https://huggingface.co/lemonilia/limarp-llama2/tree/main

**Comment by Nixellion** [comment]
Well, I just tried the "convert all" fix from here: https://github.com/turboderp/exllama/issues/180#issuecomment-1646560967

And it works great for limarp lora on top of bloke's llama 2 gptq model. In fact so far I'm blown away by it's coherency in roleplays. It even respects corrections and OOC talk in brackets. It does not feel like it's 13B even.

**Comment by turboderp** [comment]
Okay, I'll add the conversion for bfloat16 at least if it seems to be okay.

**Comment by BugReporterZ** [comment]
I tested these changes via oobabooga text-generation-webui and they work for me. So I guess this issue can be closed.
