### ISSUE TITLE
How to shard model and batched cache equally?

### ISSUE THREAD

**Issue by nivibilla** [turboderp/exllama#206]
Im trying to shard a 13B model over 4 gpu, and have the batch size 4x the one I can do on a single gpu. How can I do this?

**Comment by nivibilla** [comment]
![image](https://github.com/turboderp/exllama/assets/26687662/8c7224f0-2e7d-49d7-b531-3d1e26789755)

**Comment by nivibilla** [comment]
![image](https://github.com/turboderp/exllama/assets/26687662/ffcc9b66-381e-4f50-a87a-3d90ca155e86)

**Comment by turboderp** [comment]
The `config.auto_map` setting determines the amount of memory, in GB, to use on each device for *weights*. So usually if you've got 4 GPUs you want to use equally, you also want a quarter of the weights on each device. The cache will be allocated accordingly since it has to align with the layers of the model. The last entry you can just leave at some high number so the last GPU gets whatever is left over. For a 13B model you'd probably want to use something like `[1.7, 1.7, 1.7, 22]`.

**Comment by nivibilla** [comment]
Ah okay thanks, I will try this out
