### ISSUE TITLE
TransformerEngine FP8 support

### ISSUE THREAD

**Issue by SinanAkkoyun** [turboderp/exllama#21]
Hello! Could this work utilize the new H100 TransformerEngine for speedup? If yes, I would be very interested in that and would also pay your H100 cloud GPU access if you could estimate how long you will need it

Thank you very much!

**Comment by SinanAkkoyun** [comment]
I see, thank you very much for the elaborate evaluation of TE, that really helps me a lot to gain insight on the topic. Thank you very much for your work, 151tps are some really mind bending numbers!

**Comment by green-s** [comment]
The readme only mentions the H100 but Ada (4000 series) is Compute 8.9 which includes a number of the same improvements, [including FP8](https://github.com/NVIDIA/TransformerEngine/blob/37bbfc76fe9cc062a546ee7273c66a3a7eaa6b9c/transformer_engine/jax/fp8.py#L32).

**Comment by turboderp** [comment]
It does look like the 4090 has some FP8 support, despite NVIDIA's announcements, but I don't really want to write too much code that's incompatible with the 3090. At least for the time being. It's also questionable where FP8 could be useful since FP16 is already having a small (but measurable) impact on overall accuracy. Closing this for now.
