### ISSUE TITLE
WebUI Multi-bot

### ISSUE THREAD

**Issue by Fairfax-Mooresby** [turboderp/exllama#26]
Anything i need to do to make this work? simply adding names doesn't change anything. I've also tried creating prompt text files to match the name added, but no change.

Other than that it's working pretty well for talking to one bot.

**Comment by turboderp** [comment]
The logic is like this:

When you have zero participants, It simply generates responses.

When you have two participants, the response is always prefixed with the name of the second participant. You get a completion from the prompt `"<history>\n<bot name>:"`, basically.

With multiple bots, it will repeatedly complete `"<history>\n"` instead. And it starts the generation with constraints that only allow it to generate a certain number of prefixes.

- On the first round, the prefix can be any of the bot names
- From the second round, the username is also a valid prefix
- Each round removes the previously chosen prefix from the list of allowed prefixes
- If the username prefix is generated, it rewinds to just before that and considers it the end of the list of responses

So it's the model itself that decides who responds by emulating the structure of a multi-user chat, while the constraints make sure that at least one bot responds, and each bot can only respond once for every user input (unless you just hit enter on a blank input, which starts a new round without user input.)

As such it probably won't work great with certain finetunes, especially if they're tuned exclusively for interactions between a single user and a single bot. I found that WizardLM-uncensored works pretty well, as does base Llama with enough parameters.

The prompt for the example in the screenshot, for reference is:

    Batman, Superman and Conan The Barbarian team up with Dora The Explorer.

Specifically addressing the bots you want to respond also helps. Basically treat it like a multi-user chat or a movie script or play, and it should be alright. Since it's the language model that chooses, a good enough model can also do it smartly. E.g. when Batman addresses Superman as "Clark", Superman is likely to respond because it makes sense that Batman knows Superman's secret identity.

One other thing to consider is that language models really like to repeat themselves. If you have a lot of interactions in the history between two participants, especially small models tend to get stuck in that pattern.

**Comment by Fairfax-Mooresby** [comment]
Ah cool, i've got it working now. thanks. I had my mind set in the group chat feature of tavern, but this actually seems better. Using bluemoonrp-30b-4bit-128g with Sequence length: 4096, the large context should help a bit I think.

**Comment by turboderp** [comment]
Does Bluemoon actually work with that sequence length?
