### ISSUE TITLE
"ValueError: Found group index but no groupsize. What do?"

### ISSUE THREAD

**Issue by dvoidus** [turboderp/exllama#44]
Getting subj exception with new model from here: https://huggingface.co/TheBloke/tulu-30B-GPTQ

**Comment by turboderp** [comment]
Yeah, I've always wondered what to do in this situation, but it's never actually come up before. I guess because having a group index without any groups doesn't make sense for GPTQ. I'll have to investigate.

**Comment by turboderp** [comment]
Okay, it wasn't complicated. It's just another model that's listed as act-order but doesn't load or run like an act-order model at all. Only this time, instead of having no group index, it had an empty (all-zero) group index instead. This probably also explains why the model wouldn't work on the GPTQ Triton branch. And if I'm not mistaken it'll run somewhat slower on the GPTQ CUDA branch than it needs to.

I'm still not sure what the deal is, but anyway, I added a check to discard the group index at load time if it's empty and redundant, and the model seems to work.

**Comment by dvoidus** [comment]
I think you need to patch model.py with something like:

```
diff --git a/model.py b/model.py
index 0f31ce7..55f1cb4 100644
--- a/model.py
+++ b/model.py
@@ -116,7 +116,7 @@ class Ex4bitLinear:
         self.g_idx = tensors[key + ".g_idx"].cpu() if key + ".g_idx" in tensors else None
         self.bias = tensors[key + ".bias"] if has_bias else None

-        if (self.g_idx == 0).all():
+        if self.g_idx is not None and (self.g_idx == 0).all():
             self.config.empty_g_idx = True
             self.g_idx = None
```

Otherwise it crashes with the models that are unaffected by the fix:
```
  File "/home/dima/exllama/model.py", line 120, in __init__
    if (self.g_idx == 0).all():
AttributeError: 'bool' object has no attribute 'all'
```

**Comment by turboderp** [comment]
Yep, you're right. Fixed it.
