### ISSUE TITLE
how to get correct model type?

### ISSUE THREAD

**Issue by lx0126z** [turboderp/exllama#49]
my original model is a .bin file, then i use the below code to convert the model format

model = AutoModelForCausalLM.from_pretrained("path/to/llama_7b", torch_dtype=torch.float16,device_map='auto' )
model.save_pretrained('path/to/exllama',safe_serialization=True, max_shard_size="200GB")

but when i run  test_benchmark_inference.py , i meet mistake 
![image](https://github.com/turboderp/exllama/assets/122880585/325ee779-9aa3-4d6f-ace2-b79647150b3e)
the model didn't have qzeros/scales

how can i deal with it, could you help me?

**Comment by turboderp** [comment]
The model needs to be quantized with GPTQ-for-LLaMA or AutoGPTQ. There are a bunch of compatible GPTQ models [here](https://huggingface.co/TheBloke). Alternatively, [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) has an example of how to produce a quantized model.

**Comment by lx0126z** [comment]
Thank you! I successfully ran it. 
However, when I ran the test_inference.py script, I noticed that the generation speed is only 25 tokens per second. 
Is this due to the GPU or do I need to set other arguments?

model: llama30b
gpu: 3090

**Comment by Ph0rk0z** [comment]
Check your torch install.

**Comment by turboderp** [comment]
@lx0126z : I'm not sure what you mean by "only" 25 tokens/second. That's a lot for a 30B model, and only a little less than I'm getting on my 3090-Ti.

I do believe the 3090 should be able to get much closer to the 4090's 40+ tokens/second, since it has the bandwidth it needs, but it's also a different hardware architecture so it probably needs a bunch more tuning specific to the 3090 to make it happen.
