### ISSUE TITLE
Working with TheBloke/WizardLM-30B-Uncensored-GPTQ

### ISSUE THREAD

**Issue by gabriel-peracio** [turboderp/exllama#5]
Hi! I got this to work with [TheBloke/WizardLM-30B-Uncensored-GPTQ](https://huggingface.co/TheBloke/WizardLM-30B-Uncensored-GPTQ).

Here's what worked:
1. This doesn't work on windows, but it does work on WSL
2. Download the model (and all files) from HF and place it somewhere. Put this somewhere inside the wsl linux filesystem, not under `/mnt/c/somewhere` otherwise the model loading will be mega slow regardless of your disk speed
3. on `model.py` I added the following:
```python
        # self.groupsize = (self.qweight.shape[0] * 8) // self.qzeros.shape[0]
        self.groupsize = None
        self.config.groupsize = None
        self.config.act_order = True

        # self.config.groupsize = self.groupsize
        # if self.config.groupsize is None:
        #     self.config.groupsize = self.groupsize
        # else:
        #     if self.config.groupsize != self.groupsize:
        #         raise ValueError("Irregular groupsize for matrix: " + key + ", " + str(self.config.groupsize) + ", "+ str(self.groupsize))
```
Note the commented out code and the additions
4. I had to use `-mm pytorch_only` and `-a pytorch_matmul`

**Comment by turboderp** [comment]
That's helpful. I'll look into it. Probably just yet another variant of GPTQ to consider.

**Comment by turboderp** [comment]
I pushed an update now to deal with weights without groupsize. Seems to work here at least, also with the quantized matmul to give 33 tokens/second on my setup. So you wouldn't need `-mm pytorch_only` or to disable groupsize detection. Curious to hear if it did the trick on Windows as well.

Also, are you sure you needed the `-a pytorch_matmul` argument? Cause that would be a completely separate issue if `scaled_dot_product_attention()` doesn't work, since attention doesn't touch the quantized matrices at all. Maybe you're on PyTorch 1.x?

**Comment by turboderp** [comment]
This issue seems to have gotten forgotten, but yeah, you should be getting better speeds than that. A lot has changed in the last three weeks, so you could try with the latest version. Also the Windows native version seems to be faster, at least for some people, using Hardware Accelerated GPU Scheduling. So that could be a thing to try.
