### ISSUE TITLE
About Llama checkpoint 4-bit

### ISSUE THREAD

**Issue by Iambestfeed** [turboderp/exllama#94]
After researching about the GPTQ repo, I noticed an [issue](https://github.com/IST-DASLab/gptq/issues/2) as follows:
![image](https://github.com/turboderp/exllama/assets/95571916/39eb15a8-869e-4e5d-a65b-03f9106937b6)
After looking through this repo's llama.py code, I've never seen a save feature and it doesn't seem like they really support 4-bit (as the issue mentioned above).

So my question is am I missing any information here or is GPTQ not really important and directly affects exllama as I thought?

**Comment by turboderp** [comment]
ExLlama uses GPTQ weights produced by AutoGPTQ or GPTQ-for-LLaMA or some other tool. It doesn't have a save feature because it's not a conversion tool, just an inference engine.

I guess based on that exchange at least the original GPTQ implementation could save intermediate checkpoints that were "fake" quantized, i.e. just FP16 tensors with the effects of quantization applied. But ExLlama wouldn't be able to load those either.

**Comment by Iambestfeed** [comment]
> ExLlama uses GPTQ weights produced by AutoGPTQ or GPTQ-for-LLaMA or some other tool. It doesn't have a save feature because it's not a conversion tool, just an inference engine.
> 
> I guess based on that exchange at least the original GPTQ implementation could save intermediate checkpoints that were "fake" quantized, i.e. just FP16 tensors with the effects of quantization applied. But ExLlama wouldn't be able to load those either.

Oh, so I should actually understand that ExLlama is solely focused on implementing inference for a model based on the LLaMA architecture with the best possible resource optimization, right? (The matter of storage optimization is not something to be discussed in this repository, is it?)

**Comment by turboderp** [comment]
I've considered adding options to also *produce* quantized models, but currently that's outside the scope of the project, yes.
